=== ekoliving/Meemplex/internet-xmlrpc/documentation/tutorial.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    DTD for Majitek tutorial/documentation files
-->

<!ENTITY esys "EdgeSystem" >
<!ENTITY esc  "EdgeSystem Console" >
<!ENTITY im   "InterMajik" >
<!ENTITY es   "EdgeServer" >
<!ENTITY ms   "MeemSpace" >
<!ENTITY hs   "HyperSpace" >
<!ENTITY msr  "MeemServer" >
<!ENTITY mst  "MeemStore" >
<!ENTITY majitekurl  "http://www.majitek.com" >
<!ENTITY storefronturl   "https://secure.majitek.com" >
<!ENTITY jdkversion "1.4.x" >

<!ELEMENT Book       (document+) >

<!ELEMENT document   (header?, body) >
<!ATTLIST document   root      CDATA     #IMPLIED >

<!ELEMENT header     (style-sheet) >

<!ELEMENT section-title 
                     (#PCDATA | productname)* >

<!ELEMENT section-subtitle 
                     (#PCDATA | productname)* >

<!ELEMENT style-sheet 
                     (#PCDATA) >

<!ELEMENT body       (page-heading | section-title | section-subtitle |
                              tut-oview | tut-section | incl | code-samples |
                              more-info)* >
                              
<!ELEMENT fragment   (tut-section | code-samples | more-info)* >

<!ELEMENT incl       EMPTY >
<!ATTLIST incl href  CDATA #REQUIRED >

<!ELEMENT page-heading 
                     (#PCDATA | inline-code | index-term | productname)* >

<!ELEMENT tut-oview  (paragraph+) >

<!ELEMENT tut-section 
                     (section-heading | section-subheading | paragraph |
                              code | indent-code | pre | image | codebox |
                              glossary | index-phrase)* >

<!ELEMENT glossary   (entry) >

<!ELEMENT entry      (index-term*, term, def)+ >

<!ELEMENT term       (#PCDATA) >

<!ELEMENT productname       (#PCDATA) >

<!ELEMENT def        (#PCDATA | iref | fig | table)* >

<!--iref: internal ref to another glossary term-->
<!ELEMENT iref       (#PCDATA) >

<!--fig: source file for graphic-->
<!ELEMENT fig        EMPTY >
<!ATTLIST fig        src       CDATA     #REQUIRED >

<!ELEMENT paragraph  (#PCDATA | usertype | inline-code | ordered-list |
                              ordered-list-continue | unordered-list | emph |
                              token | menu-selection | user-entry | note |
                              image | inline-image | table | index-phrase |
                              index-term | important | link | external-link |
                              menu-cmd | inlinetext | reminder | productname)* >

<!--code: When embedded in <item>, prefix with newline to avoid sub-item in
 numbered list.-->
<!ELEMENT code       (#PCDATA | hilite | block-hilite | index-term |
                              index-phrase | token)* >

<!ELEMENT indent-code 
                     (#PCDATA | hilite | block-hilite | index-term |
                              index-phrase | token)* >

<!ELEMENT pre        (#PCDATA | hilite | block-hilite | newline)* >

<!ELEMENT inline-code 
                     (#PCDATA | token)* >

<!ELEMENT section-heading 
                     (#PCDATA | inline-code | productname)* >

<!ELEMENT section-subheading 
                     (#PCDATA | inline-code | index-term | productname)* >

<!ELEMENT more-info  (unordered-list) >

<!ELEMENT code-samples 
                     (unordered-list) >

<!ELEMENT unordered-list 
                     (item+) >

<!ELEMENT ordered-list 
                     (item+) >

<!ELEMENT ordered-list-continue 
                     (item+) >

<!ELEMENT item       (#PCDATA | link | external-link | menu-selection |
                              user-entry | note | token | image | index-phrase
                              | index-term | hilite | inline-code | code | emph |
                              item | unordered-list | ordered-list | table |
                              inline-image | menu-cmd | usertype |
                              inlinetext | reminder | productname)* >

<!ELEMENT link       (name, url?) >

<!ELEMENT external-link 
                     (name, exturl) >

<!ELEMENT name       (#PCDATA) >

<!ELEMENT reminder       (#PCDATA | emph)* >

<!ELEMENT exturl     (#PCDATA) >

<!ELEMENT url        (#PCDATA) >

<!ELEMENT emph       (#PCDATA) >

<!ELEMENT token      (#PCDATA) >

<!ELEMENT menu-selection 
                     (#PCDATA) >

<!ELEMENT user-entry (#PCDATA) >

<!ELEMENT note       (#PCDATA | inline-code | productname)* >

<!ELEMENT important  (#PCDATA | inline-code | productname)* >

<!ELEMENT image      EMPTY >
<!ATTLIST image      file      CDATA     #REQUIRED
                     dpi       CDATA   #FIXED "96"
                     angle     (270)     #IMPLIED
                     w         CDATA     #IMPLIED
                     imgsize   CDATA     #IMPLIED
                     import    CDATA     #IMPLIED
                     crop      CDATA     #IMPLIED
                     posn      CDATA     #IMPLIED
                     entity    ENTITY    #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     height    CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED >

<!ELEMENT inline-image 
                     EMPTY >
<!ATTLIST inline-image 
                     file      CDATA     #REQUIRED
                     w         CDATA     #IMPLIED
                     dpi       NMTOKEN   #FIXED "96"
                     imgsize   CDATA     #IMPLIED
                     align     CDATA     #IMPLIED
                     ref       CDATA     #IMPLIED
                     bloff     CDATA     #IMPLIED
                     posn      CDATA     #IMPLIED
                     txt       CDATA     #IMPLIED
                     entity    ENTITY    #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED >

<!--table: cwidths in form "2cm 3cm" (set values as required) 
  are required for framemaker rendition, not
 XSL. See Structured Apps Dev Guide p277.
 e.g. <table cols="3" cwidths="2cm 2cm 5cm">
 -->
<!ELEMENT table      (th*, tbody) >
<!ATTLIST table      cols      NMTOKEN   #REQUIRED
                     cwidths   CDATA     #IMPLIED >

<!ELEMENT th         (hrow+) >

<!ELEMENT tbody      (row+) >

<!ELEMENT row        (cell+) >

<!ELEMENT hrow       (hcell+) >

<!ELEMENT cell       (#PCDATA | inline-code | emph | inline-image | image | productname)* >

<!ELEMENT hcell      (#PCDATA | inline-code | emph)* >

<!ELEMENT codebox    (((pre))) >

<!ELEMENT block-hilite 
                     (#PCDATA) >

<!ELEMENT hilite     (#PCDATA) >

<!ELEMENT usertype   (#PCDATA) >

<!ELEMENT menu-cmd   (#PCDATA) >

<!ELEMENT index-term EMPTY >
<!ATTLIST index-term 
                     type      CDATA     #IMPLIED
                     text      CDATA     #IMPLIED >

<!ELEMENT index-phrase 
                     EMPTY >
<!ATTLIST index-phrase 
                     txt       CDATA     #IMPLIED
                     type      CDATA     #IMPLIED >

<!ELEMENT inlinetext (#PCDATA) >

<!ELEMENT newline    EMPTY >

=== ekoliving/Meemplex/internet-xmlrpc/documentation/xmlrpc01.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="transform-browser.xsl"?>
<!DOCTYPE document SYSTEM "tutorial.dtd" >

<document root=".">
<header>

<style-sheet>./stylesheet.css</style-sheet>
</header>
<body>
<page-heading>XML-RPC Interface for non-Maji Applications</page-heading>
<tut-oview><paragraph>
In this topic you will learn how to use the XML-RPC interface for connecting non-Maji 
applications to applications developed in the Maji framework.
</paragraph>
</tut-oview>

<tut-section>
<index-phrase txt="XML-RPC"/>
<index-phrase txt="Non-Maji applications, interfacing via XML-RPC"/>
<section-subheading></section-subheading>
<paragraph> 
The Maji RPC API provides a way for non-Maji applications to interact with a Maji system.
Currently a Java API is provided, but in the future C++, Javascript, PHP and other 
languages may be supported.</paragraph>
<paragraph>The non-Maji application interacts with Facets in Maji via 
bindings.  These bindings then communicate over XML-RPC as the following diagram
illustrates.</paragraph>
<image file="images/xmlrpc-01.gif" dpi="96"/>
</tut-section>

<tut-section>
<section-heading>How to Use XML-RPC with Maji</section-heading>
<index-phrase txt="XML-RPC, using with Maji"/>
<section-subheading>Creating and Configuring a Maji RPC Server</section-subheading>
<paragraph>In order for RPC clients to connect to a Maji system, 
a Maji RPC Server Meem must be created.  
This Meem starts a server that the clients connect to and interact with.</paragraph>
<paragraph>To create a <inline-code>MajiRPCServerMeem</inline-code>,
<ordered-list>
    <item>Start Intermajik and create a worksheet in a suitable Category</item>
    <item>In the Meem Toolkit, navigate to gateway | rpc</item>
    <item>Drag MajiRPCServer onto your worksheet</item>
    <item>Configure the Server using the settings in the following table.</item>
</ordered-list>
<table cols="2" cwidths="4cm 8cm">
    <th>
        <hrow>
            <hcell>Property</hcell>
            <hcell>Description</hcell>
        </hrow>
    </th>
    <tbody>
        <row>
            <cell>port</cell>
            <cell>The IP port for the Server to listen on</cell>
        </row>
        <row>
            <cell>useSSL</cell>
            <cell>Whether SSL should be used.  You should use SSL 
to prevent your information from being viewed by unauthorised users on the network.</cell>
        </row>
        <row>
            <cell>sslKeystore</cell>
            <cell>The path to the keystore which contains the certificate for the server. 
This is used when  the useSSL property is set to true.  
The key used is stored under the "jetty" alias</cell>
        </row>
        <row>
            <cell>sslPassword</cell>
            <cell>The password to use for accessing the keystore</cell>
        </row>
        <row>
            <cell>sslKeyPassword</cell>
            <cell>The password required for accessing the key for "jetty"</cell>
        </row>
        <row>
            <cell>needClientAuth</cell>
            <cell>Whether client are required to authenticate themselves with a certificate.</cell>
        </row>                                        
    </tbody>
</table>
</paragraph>
<paragraph>

</paragraph>
<section-subheading>Using Java Client Bindings for RPC</section-subheading>
<index-phrase txt="MajiRPCClient object"/>
<index-phrase txt="RPC - MajiRPCClient object"/>
<paragraph>Create a MajiRPCClient object and set the username, password
and address of the RPC server as follows:
</paragraph>
<codebox>
<pre>
    MajiRPCClient rpcClient = new MajiRPCClient();
    rpcClient.setUsername("myusername");
    rpcClient.setPassword("secret");
    rpcClient.setAddress("http://myhost:8000/maji/rpc");
</pre>
</codebox>
</tut-section>
<tut-section>
<section-heading>Creating Bindings</section-heading>
<index-phrase txt="RPC bindings"/>
<paragraph>A binding is required for each Facet that the client application is to interact with.  
Bindings are either inbound or outbound.  Inbound bindings receive messages from the outbound 
Facets of Meems on the Maji Server, while outbound bindings send messages to the inbound 
Facets of Meems on a Maji Server.</paragraph>
<section-subheading>Outbound Bindings</section-subheading>

<paragraph>The <inline-code>BindingFactory</inline-code> is used to create an outbound binding:</paragraph>
<code>Binary outbound = (Binary) BindingFactory.createOutbound(Binary.class);
</code>
<paragraph>You must also set the properties of the facet you wish to receive information 
from and configure the binding to send events to the RPC client as the following
code shows.</paragraph>
<codebox>
<pre>
    
    //  The MeemPath may be a Hyperspace address or an address in MeemRegistry
    outbound.setMeemPath("hyperspace:/user/guest/test/LoopbackBinary");
    // The Facet identifier is the name of the Facet on the Meem to bind to
    outbound.setFacetId("binaryInput");
    // Configure the binding to send events to the RPCClient which, in turn, 
    // sends the messages to the Maji Server
    outbound.setFacetEventReceiver(rpcClient);
</pre>
</codebox>   

<section-subheading>Inbound Bindings</section-subheading>
<paragraph>The <inline-code>BindingFactory</inline-code> is also used to create an 
inbound binding to the outbound Facet in the Maji server,

</paragraph>
<codebox>
<pre>
    Binary inbound = (Binary) BindingFactory.createInbound(Binary.class);
    // Set the MeemPath to the Meem on the Maji Server    
    inbound.setMeemPath("hyperspace:/user/guest/test/LoopbackBinary");
    // Set the FacetId to the name of the Facet within the Meem to bind to:
    inbound.setFacetId("binaryOutput");
    // Configure the binding to receive events from the RPCClient that 
    // receives messages from the Maji Server:
    inbound.setFacetEventSender(rpcClient);
</pre>
</codebox>
</tut-section>

<tut-section>
<section-heading>Meem Lifecycle State</section-heading>

<paragraph>Programs can listen to the MajiRPCClient for the status of the Facets that are bound. This will
enable you to find out whether the Meem has been located and resolved and what the 
lifecycle state of the Meem is.</paragraph>

<paragraph>
	The <inline-code>MajiRPCClient</inline-code> implements the <inline-code>FacetHealthEventSender</inline-code> interface.

	This means that you may create an object that implements <inline-code>FacetHealthListener</inline-code> and 
	tell <inline-code>MajiRPCClient</inline-code> to send events to it by calling
	<inline-code>MajiRPCClient.addFacetHealthListener(FacetHealthListener listener)</inline-code>
</paragraph>
<paragraph>
	To remove the listener, call
	<inline-code>MajiRPCClient.removeFacetHealthListener(FacetHealthListener listener)</inline-code>
</paragraph>

<paragraph>
MajiRPCClient will send FacetHealthEvents for each Facet.  
These events can be used to determine the following states of a binding:
	<unordered-list>
    <item>RPC disconnected</item>
    <item>Meem not resolved</item>
	<item>Meem resolved</item>
	<item>Facet resolved</item>
	</unordered-list>
</paragraph>
<paragraph>
	It is intended that Lifecycle state will also be delivered via the FacetHealthListener interface.
</paragraph>
</tut-section>

<tut-section>
<section-heading>Creating and Registering new Bindings</section-heading>
<index-phrase txt="RPC bindings - creating and registering"/>
<section-subheading>Creating Outbound Bindings</section-subheading>

<paragraph>Outbound bindings are required to translate parameters of method calls in the Facet 
interface to types that can be sent via XML-RPC.  The types that can be sent over XML-RPC 
are shown in the following table.
<table cols="2" cwidths="4cm 8cm">
    <th>
        <hrow>
            <hcell>XML-RPC data type</hcell>
            <hcell>Corresponding Java type</hcell>
        </hrow>
    </th>
    <tbody>
        <row>
            <cell>i4 or int</cell>
            <cell>java.lang.Integer</cell>
        </row>
        <row>
            <cell>boolean</cell>
            <cell>java.lang.Boolean</cell>
        </row>
        <row>
            <cell>string</cell>
            <cell>java.lang.String</cell>
        </row>
        <row>
            <cell>double</cell>
            <cell>java.lang.Double</cell>
        </row>
        <row>
            <cell>dateTime.iso8601</cell>
            <cell>java.util.Date</cell>
        </row>
        <row>
            <cell>struct</cell>
            <cell>java.util.Hashtable</cell>
        </row>
        <row>
            <cell>array</cell>
            <cell>java.util.Vector</cell>
        </row>
        <row>
            <cell>base64</cell>
            <cell>byte[]</cell>
        </row>
    </tbody>
</table>
An outbound binding must subclass <inline-code>OutboundBinding</inline-code>.
The developer must implement the methods of the Facet interface relevant to the binding.  
The bodies of the methods make a call to the send method of the 
<inline-code>OutboundBinding</inline-code> superclass:
</paragraph>

<code>
    send(String methodName, Object[] parameters)
</code>
<paragraph>
as the following example shows:
</paragraph>
<codebox>
<pre>
    public void valueChanged(Position p) {

      Object value = null;
      if (p instanceof IntegerPosition) {
        value = new Integer(p.intValue());
      }
      else {
        value = new Double(p.doubleValue());
      }
      send("valueChanged", new Object[] { value });
      }
</pre>
</codebox>

<section-subheading>Creating Inbound Bindings</section-subheading>

<paragraph>An inbound binding must subclass <inline-code>InboundBinding</inline-code>.
The constructor must make a call to <inline-code>setFacetClass(Class)</inline-code> to set
the Facet interface this binding relates to, for example:
</paragraph>
<code>    setFacetClass(Linear.class);</code>

<paragraph>The following methods must be implemented on the outbound binding:
<unordered-list>
